"""initial schema

Revision ID: 6186e1fa4a22
Revises: 
Create Date: 2026-05-11 09:21:46.760835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6186e1fa4a22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Enum('G', 'PG', 'PG13', 'R', 'NC17', name='movierating'), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_table('screens',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('screen_type', sa.Enum('STANDARD', 'IMAX', 'THREE_D', 'FOUR_D', 'DOLBY', name='screentype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('seats',
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('row', sa.String(length=5), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('REGULAR', 'VIP', 'HANDICAP', name='seattype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'row', 'number', name='uq_seat_screen_row_number')
    )
    op.create_index(op.f('ix_seats_screen_id'), 'seats', ['screen_id'], unique=False)
    op.create_table('showtimes',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_regular', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_vip', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'start_time', name='uq_showtime_screen_start')
    )
    op.create_index(op.f('ix_showtimes_movie_id'), 'showtimes', ['movie_id'], unique=False)
    op.create_index(op.f('ix_showtimes_screen_id'), 'showtimes', ['screen_id'], unique=False)
    op.create_table('bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_showtime_id'), 'bookings', ['showtime_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('booking_seats',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seat_id', 'showtime_id', name='uq_booking_seat_per_showtime')
    )
    op.create_index(op.f('ix_booking_seats_booking_id'), 'booking_seats', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_seats_showtime_id'), 'booking_seats', ['showtime_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'PAYPAL', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_booking_seats_showtime_id'), table_name='booking_seats')
    op.drop_index(op.f('ix_booking_seats_booking_id'), table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_showtime_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_showtimes_screen_id'), table_name='showtimes')
    op.drop_index(op.f('ix_showtimes_movie_id'), table_name='showtimes')
    op.drop_table('showtimes')
    op.drop_index(op.f('ix_seats_screen_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('screens')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
